# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OuiCar Tech Blog
email: contact@ouicar.fr
description: A blog where we talk about the technologies we use at OuiCar.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ouicar.github.io/" # the base hostname & protocol for your site
twitter_username: ouicar
github_username:  ouicar

# Build settings
markdown: kramdown
